#!/usr/bin/env bash

set -e

BIN=${1:-xmonad}

# xmonad likes to rebuild itself at inappropriate moments. Disable building
# unless we actually want it.
if [[ "$2" == "yes" ]]; then
  shift
  stack install --ghc-options -j --local-bin-path "$PWD"
  [[ -f $BIN ]] || ln -s xmonad "$BIN"
else
  echo "Run like: $0 yes"
fi
